#! /usr/bin/env bash

ANADIR=src/Analyses

for t in $(hg tags | cut -d" " -f1 | sort -r); do
    epoch=$(hg parent --rev $t -T "{date}")
    nanas=$(hg st -n --rev 0 --rev $t $ANADIR/*.cc | wc -w)
    echo "$t $epoch $nanas"
done
