#! /usr/bin/env bash

for t in $(hg tags | cut -d" " -f1 | sort -r); do
    epoch=$(hg parent --rev $t -T "{date}")
    nanas=$(hg st -n --rev 0 --rev $t analyses/ src/Analyses/ | grep '.cc' | wc -w)
    echo "$t $epoch $nanas"
done
