#! /usr/bin/env bash

# TODO: rewrite in Python using hglib?

echo -e "Rivet analysis diffs\n====================\n"

declare -a tags
for t in $(hg tags | egrep "^rivet-2" | cut -d" " -f1 | sort); do tags+=($t); done
tags+=(tip)
let numtags=${#tags[@]}
let numdiffs=$numtags-1
let N=$numdiffs-1
for i in `seq 0 $N`; do
    let j=$i+1
    rev0=${tags[$i]}
    rev1=${tags[$j]}
    echo "$rev0 -> $rev1"

    anas=$(for i in $(hg st -na --rev $rev0 --rev $rev1 src/Analyses/*.cc); do echo $(basename $i .cc); done)
    test "$anas" && { echo -e "\n  Added:"; echo $anas | xargs rivet --list-analyses | while read l; do echo "    $l"; done; }

    anas=$(for i in $(hg st -nm --rev $rev0 --rev $rev1 src/Analyses/*.cc); do echo $(basename $i .cc); done)
    test "$anas" && { echo -e "\n  Modified:"; echo $anas | xargs rivet --list-analyses | while read l; do echo "    $l"; done; }

    anas=$(for i in $(hg st -nr --rev $rev0 --rev $rev1 src/Analyses/*.cc); do echo $(basename $i .cc); done)
    test "$anas" && { echo -e "\n  Removed:"; echo $anas | xargs rivet --list-analyses | while read l; do echo "    $l"; done; }

    echo
done
