#! /usr/bin/env bash
## -*- sh -*-

thisdir=`dirname $0`
export RIVET_ANALYSIS_PATH=$thisdir
echo -n "List of analyses includes MYANALYSIS? "
$thisdir/../bin/rivet --list-analyses | grep --color=auto MYANALYSIS &> /dev/null
RESULT=$?
if [[ $RESULT -eq 0 ]]; then
    echo YES
    exit 0
else
    echo NO
    exit $RESULT
fi
