#! /usr/bin/env bash

RANKFILES=$(echo *.rank)
BASECMD='./mk-rivethd-html *.json -r "$RANKFILES" -R'

eval "$BASECMD"
eval "$BASECMD -SI"
eval "$BASECMD -S"
eval "$BASECMD -I"
eval "$BASECMD -s"
eval "$BASECMD -i"
